/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.is.vision.CameraSettings');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.is.vision.CameraSetting');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.is.vision.CameraSettings = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.is.vision.CameraSettings, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.is.vision.CameraSettings.displayName = 'proto.is.vision.CameraSettings';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.is.vision.CameraSettings.prototype.toObject = function(opt_includeInstance) {
  return proto.is.vision.CameraSettings.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.is.vision.CameraSettings} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.is.vision.CameraSettings.toObject = function(includeInstance, msg) {
  var f, obj = {
    brightness: (f = msg.getBrightness()) && proto.is.vision.CameraSetting.toObject(includeInstance, f),
    exposure: (f = msg.getExposure()) && proto.is.vision.CameraSetting.toObject(includeInstance, f),
    focus: (f = msg.getFocus()) && proto.is.vision.CameraSetting.toObject(includeInstance, f),
    gain: (f = msg.getGain()) && proto.is.vision.CameraSetting.toObject(includeInstance, f),
    gamma: (f = msg.getGamma()) && proto.is.vision.CameraSetting.toObject(includeInstance, f),
    hue: (f = msg.getHue()) && proto.is.vision.CameraSetting.toObject(includeInstance, f),
    iris: (f = msg.getIris()) && proto.is.vision.CameraSetting.toObject(includeInstance, f),
    saturation: (f = msg.getSaturation()) && proto.is.vision.CameraSetting.toObject(includeInstance, f),
    sharpness: (f = msg.getSharpness()) && proto.is.vision.CameraSetting.toObject(includeInstance, f),
    shutter: (f = msg.getShutter()) && proto.is.vision.CameraSetting.toObject(includeInstance, f),
    whiteBalanceBu: (f = msg.getWhiteBalanceBu()) && proto.is.vision.CameraSetting.toObject(includeInstance, f),
    whiteBalanceRv: (f = msg.getWhiteBalanceRv()) && proto.is.vision.CameraSetting.toObject(includeInstance, f),
    zoom: (f = msg.getZoom()) && proto.is.vision.CameraSetting.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.is.vision.CameraSettings}
 */
proto.is.vision.CameraSettings.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.is.vision.CameraSettings;
  return proto.is.vision.CameraSettings.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.is.vision.CameraSettings} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.is.vision.CameraSettings}
 */
proto.is.vision.CameraSettings.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.is.vision.CameraSetting;
      reader.readMessage(value,proto.is.vision.CameraSetting.deserializeBinaryFromReader);
      msg.setBrightness(value);
      break;
    case 2:
      var value = new proto.is.vision.CameraSetting;
      reader.readMessage(value,proto.is.vision.CameraSetting.deserializeBinaryFromReader);
      msg.setExposure(value);
      break;
    case 3:
      var value = new proto.is.vision.CameraSetting;
      reader.readMessage(value,proto.is.vision.CameraSetting.deserializeBinaryFromReader);
      msg.setFocus(value);
      break;
    case 4:
      var value = new proto.is.vision.CameraSetting;
      reader.readMessage(value,proto.is.vision.CameraSetting.deserializeBinaryFromReader);
      msg.setGain(value);
      break;
    case 5:
      var value = new proto.is.vision.CameraSetting;
      reader.readMessage(value,proto.is.vision.CameraSetting.deserializeBinaryFromReader);
      msg.setGamma(value);
      break;
    case 6:
      var value = new proto.is.vision.CameraSetting;
      reader.readMessage(value,proto.is.vision.CameraSetting.deserializeBinaryFromReader);
      msg.setHue(value);
      break;
    case 7:
      var value = new proto.is.vision.CameraSetting;
      reader.readMessage(value,proto.is.vision.CameraSetting.deserializeBinaryFromReader);
      msg.setIris(value);
      break;
    case 8:
      var value = new proto.is.vision.CameraSetting;
      reader.readMessage(value,proto.is.vision.CameraSetting.deserializeBinaryFromReader);
      msg.setSaturation(value);
      break;
    case 9:
      var value = new proto.is.vision.CameraSetting;
      reader.readMessage(value,proto.is.vision.CameraSetting.deserializeBinaryFromReader);
      msg.setSharpness(value);
      break;
    case 10:
      var value = new proto.is.vision.CameraSetting;
      reader.readMessage(value,proto.is.vision.CameraSetting.deserializeBinaryFromReader);
      msg.setShutter(value);
      break;
    case 11:
      var value = new proto.is.vision.CameraSetting;
      reader.readMessage(value,proto.is.vision.CameraSetting.deserializeBinaryFromReader);
      msg.setWhiteBalanceBu(value);
      break;
    case 12:
      var value = new proto.is.vision.CameraSetting;
      reader.readMessage(value,proto.is.vision.CameraSetting.deserializeBinaryFromReader);
      msg.setWhiteBalanceRv(value);
      break;
    case 13:
      var value = new proto.is.vision.CameraSetting;
      reader.readMessage(value,proto.is.vision.CameraSetting.deserializeBinaryFromReader);
      msg.setZoom(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.is.vision.CameraSettings.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.is.vision.CameraSettings.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.is.vision.CameraSettings} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.is.vision.CameraSettings.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBrightness();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.is.vision.CameraSetting.serializeBinaryToWriter
    );
  }
  f = message.getExposure();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.is.vision.CameraSetting.serializeBinaryToWriter
    );
  }
  f = message.getFocus();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.is.vision.CameraSetting.serializeBinaryToWriter
    );
  }
  f = message.getGain();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.is.vision.CameraSetting.serializeBinaryToWriter
    );
  }
  f = message.getGamma();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.is.vision.CameraSetting.serializeBinaryToWriter
    );
  }
  f = message.getHue();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.is.vision.CameraSetting.serializeBinaryToWriter
    );
  }
  f = message.getIris();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.is.vision.CameraSetting.serializeBinaryToWriter
    );
  }
  f = message.getSaturation();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.is.vision.CameraSetting.serializeBinaryToWriter
    );
  }
  f = message.getSharpness();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.is.vision.CameraSetting.serializeBinaryToWriter
    );
  }
  f = message.getShutter();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.is.vision.CameraSetting.serializeBinaryToWriter
    );
  }
  f = message.getWhiteBalanceBu();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      proto.is.vision.CameraSetting.serializeBinaryToWriter
    );
  }
  f = message.getWhiteBalanceRv();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      proto.is.vision.CameraSetting.serializeBinaryToWriter
    );
  }
  f = message.getZoom();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      proto.is.vision.CameraSetting.serializeBinaryToWriter
    );
  }
};


/**
 * optional CameraSetting brightness = 1;
 * @return {?proto.is.vision.CameraSetting}
 */
proto.is.vision.CameraSettings.prototype.getBrightness = function() {
  return /** @type{?proto.is.vision.CameraSetting} */ (
    jspb.Message.getWrapperField(this, proto.is.vision.CameraSetting, 1));
};


/** @param {?proto.is.vision.CameraSetting|undefined} value */
proto.is.vision.CameraSettings.prototype.setBrightness = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.is.vision.CameraSettings.prototype.clearBrightness = function() {
  this.setBrightness(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.is.vision.CameraSettings.prototype.hasBrightness = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional CameraSetting exposure = 2;
 * @return {?proto.is.vision.CameraSetting}
 */
proto.is.vision.CameraSettings.prototype.getExposure = function() {
  return /** @type{?proto.is.vision.CameraSetting} */ (
    jspb.Message.getWrapperField(this, proto.is.vision.CameraSetting, 2));
};


/** @param {?proto.is.vision.CameraSetting|undefined} value */
proto.is.vision.CameraSettings.prototype.setExposure = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.is.vision.CameraSettings.prototype.clearExposure = function() {
  this.setExposure(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.is.vision.CameraSettings.prototype.hasExposure = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional CameraSetting focus = 3;
 * @return {?proto.is.vision.CameraSetting}
 */
proto.is.vision.CameraSettings.prototype.getFocus = function() {
  return /** @type{?proto.is.vision.CameraSetting} */ (
    jspb.Message.getWrapperField(this, proto.is.vision.CameraSetting, 3));
};


/** @param {?proto.is.vision.CameraSetting|undefined} value */
proto.is.vision.CameraSettings.prototype.setFocus = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.is.vision.CameraSettings.prototype.clearFocus = function() {
  this.setFocus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.is.vision.CameraSettings.prototype.hasFocus = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional CameraSetting gain = 4;
 * @return {?proto.is.vision.CameraSetting}
 */
proto.is.vision.CameraSettings.prototype.getGain = function() {
  return /** @type{?proto.is.vision.CameraSetting} */ (
    jspb.Message.getWrapperField(this, proto.is.vision.CameraSetting, 4));
};


/** @param {?proto.is.vision.CameraSetting|undefined} value */
proto.is.vision.CameraSettings.prototype.setGain = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.is.vision.CameraSettings.prototype.clearGain = function() {
  this.setGain(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.is.vision.CameraSettings.prototype.hasGain = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional CameraSetting gamma = 5;
 * @return {?proto.is.vision.CameraSetting}
 */
proto.is.vision.CameraSettings.prototype.getGamma = function() {
  return /** @type{?proto.is.vision.CameraSetting} */ (
    jspb.Message.getWrapperField(this, proto.is.vision.CameraSetting, 5));
};


/** @param {?proto.is.vision.CameraSetting|undefined} value */
proto.is.vision.CameraSettings.prototype.setGamma = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.is.vision.CameraSettings.prototype.clearGamma = function() {
  this.setGamma(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.is.vision.CameraSettings.prototype.hasGamma = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional CameraSetting hue = 6;
 * @return {?proto.is.vision.CameraSetting}
 */
proto.is.vision.CameraSettings.prototype.getHue = function() {
  return /** @type{?proto.is.vision.CameraSetting} */ (
    jspb.Message.getWrapperField(this, proto.is.vision.CameraSetting, 6));
};


/** @param {?proto.is.vision.CameraSetting|undefined} value */
proto.is.vision.CameraSettings.prototype.setHue = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.is.vision.CameraSettings.prototype.clearHue = function() {
  this.setHue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.is.vision.CameraSettings.prototype.hasHue = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional CameraSetting iris = 7;
 * @return {?proto.is.vision.CameraSetting}
 */
proto.is.vision.CameraSettings.prototype.getIris = function() {
  return /** @type{?proto.is.vision.CameraSetting} */ (
    jspb.Message.getWrapperField(this, proto.is.vision.CameraSetting, 7));
};


/** @param {?proto.is.vision.CameraSetting|undefined} value */
proto.is.vision.CameraSettings.prototype.setIris = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


proto.is.vision.CameraSettings.prototype.clearIris = function() {
  this.setIris(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.is.vision.CameraSettings.prototype.hasIris = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional CameraSetting saturation = 8;
 * @return {?proto.is.vision.CameraSetting}
 */
proto.is.vision.CameraSettings.prototype.getSaturation = function() {
  return /** @type{?proto.is.vision.CameraSetting} */ (
    jspb.Message.getWrapperField(this, proto.is.vision.CameraSetting, 8));
};


/** @param {?proto.is.vision.CameraSetting|undefined} value */
proto.is.vision.CameraSettings.prototype.setSaturation = function(value) {
  jspb.Message.setWrapperField(this, 8, value);
};


proto.is.vision.CameraSettings.prototype.clearSaturation = function() {
  this.setSaturation(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.is.vision.CameraSettings.prototype.hasSaturation = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional CameraSetting sharpness = 9;
 * @return {?proto.is.vision.CameraSetting}
 */
proto.is.vision.CameraSettings.prototype.getSharpness = function() {
  return /** @type{?proto.is.vision.CameraSetting} */ (
    jspb.Message.getWrapperField(this, proto.is.vision.CameraSetting, 9));
};


/** @param {?proto.is.vision.CameraSetting|undefined} value */
proto.is.vision.CameraSettings.prototype.setSharpness = function(value) {
  jspb.Message.setWrapperField(this, 9, value);
};


proto.is.vision.CameraSettings.prototype.clearSharpness = function() {
  this.setSharpness(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.is.vision.CameraSettings.prototype.hasSharpness = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional CameraSetting shutter = 10;
 * @return {?proto.is.vision.CameraSetting}
 */
proto.is.vision.CameraSettings.prototype.getShutter = function() {
  return /** @type{?proto.is.vision.CameraSetting} */ (
    jspb.Message.getWrapperField(this, proto.is.vision.CameraSetting, 10));
};


/** @param {?proto.is.vision.CameraSetting|undefined} value */
proto.is.vision.CameraSettings.prototype.setShutter = function(value) {
  jspb.Message.setWrapperField(this, 10, value);
};


proto.is.vision.CameraSettings.prototype.clearShutter = function() {
  this.setShutter(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.is.vision.CameraSettings.prototype.hasShutter = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional CameraSetting white_balance_bu = 11;
 * @return {?proto.is.vision.CameraSetting}
 */
proto.is.vision.CameraSettings.prototype.getWhiteBalanceBu = function() {
  return /** @type{?proto.is.vision.CameraSetting} */ (
    jspb.Message.getWrapperField(this, proto.is.vision.CameraSetting, 11));
};


/** @param {?proto.is.vision.CameraSetting|undefined} value */
proto.is.vision.CameraSettings.prototype.setWhiteBalanceBu = function(value) {
  jspb.Message.setWrapperField(this, 11, value);
};


proto.is.vision.CameraSettings.prototype.clearWhiteBalanceBu = function() {
  this.setWhiteBalanceBu(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.is.vision.CameraSettings.prototype.hasWhiteBalanceBu = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional CameraSetting white_balance_rv = 12;
 * @return {?proto.is.vision.CameraSetting}
 */
proto.is.vision.CameraSettings.prototype.getWhiteBalanceRv = function() {
  return /** @type{?proto.is.vision.CameraSetting} */ (
    jspb.Message.getWrapperField(this, proto.is.vision.CameraSetting, 12));
};


/** @param {?proto.is.vision.CameraSetting|undefined} value */
proto.is.vision.CameraSettings.prototype.setWhiteBalanceRv = function(value) {
  jspb.Message.setWrapperField(this, 12, value);
};


proto.is.vision.CameraSettings.prototype.clearWhiteBalanceRv = function() {
  this.setWhiteBalanceRv(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.is.vision.CameraSettings.prototype.hasWhiteBalanceRv = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional CameraSetting zoom = 13;
 * @return {?proto.is.vision.CameraSetting}
 */
proto.is.vision.CameraSettings.prototype.getZoom = function() {
  return /** @type{?proto.is.vision.CameraSetting} */ (
    jspb.Message.getWrapperField(this, proto.is.vision.CameraSetting, 13));
};


/** @param {?proto.is.vision.CameraSetting|undefined} value */
proto.is.vision.CameraSettings.prototype.setZoom = function(value) {
  jspb.Message.setWrapperField(this, 13, value);
};


proto.is.vision.CameraSettings.prototype.clearZoom = function() {
  this.setZoom(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.is.vision.CameraSettings.prototype.hasZoom = function() {
  return jspb.Message.getField(this, 13) != null;
};


