/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.is.vision.CameraConfig');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.is.common.SamplingSettings');
goog.require('proto.is.vision.CameraSettings');
goog.require('proto.is.vision.ImageSettings');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.is.vision.CameraConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.is.vision.CameraConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.is.vision.CameraConfig.displayName = 'proto.is.vision.CameraConfig';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.is.vision.CameraConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.is.vision.CameraConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.is.vision.CameraConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.is.vision.CameraConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    sampling: (f = msg.getSampling()) && proto.is.common.SamplingSettings.toObject(includeInstance, f),
    image: (f = msg.getImage()) && proto.is.vision.ImageSettings.toObject(includeInstance, f),
    camera: (f = msg.getCamera()) && proto.is.vision.CameraSettings.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.is.vision.CameraConfig}
 */
proto.is.vision.CameraConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.is.vision.CameraConfig;
  return proto.is.vision.CameraConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.is.vision.CameraConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.is.vision.CameraConfig}
 */
proto.is.vision.CameraConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.is.common.SamplingSettings;
      reader.readMessage(value,proto.is.common.SamplingSettings.deserializeBinaryFromReader);
      msg.setSampling(value);
      break;
    case 2:
      var value = new proto.is.vision.ImageSettings;
      reader.readMessage(value,proto.is.vision.ImageSettings.deserializeBinaryFromReader);
      msg.setImage(value);
      break;
    case 3:
      var value = new proto.is.vision.CameraSettings;
      reader.readMessage(value,proto.is.vision.CameraSettings.deserializeBinaryFromReader);
      msg.setCamera(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.is.vision.CameraConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.is.vision.CameraConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.is.vision.CameraConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.is.vision.CameraConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSampling();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.is.common.SamplingSettings.serializeBinaryToWriter
    );
  }
  f = message.getImage();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.is.vision.ImageSettings.serializeBinaryToWriter
    );
  }
  f = message.getCamera();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.is.vision.CameraSettings.serializeBinaryToWriter
    );
  }
};


/**
 * optional is.common.SamplingSettings sampling = 1;
 * @return {?proto.is.common.SamplingSettings}
 */
proto.is.vision.CameraConfig.prototype.getSampling = function() {
  return /** @type{?proto.is.common.SamplingSettings} */ (
    jspb.Message.getWrapperField(this, proto.is.common.SamplingSettings, 1));
};


/** @param {?proto.is.common.SamplingSettings|undefined} value */
proto.is.vision.CameraConfig.prototype.setSampling = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.is.vision.CameraConfig.prototype.clearSampling = function() {
  this.setSampling(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.is.vision.CameraConfig.prototype.hasSampling = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional ImageSettings image = 2;
 * @return {?proto.is.vision.ImageSettings}
 */
proto.is.vision.CameraConfig.prototype.getImage = function() {
  return /** @type{?proto.is.vision.ImageSettings} */ (
    jspb.Message.getWrapperField(this, proto.is.vision.ImageSettings, 2));
};


/** @param {?proto.is.vision.ImageSettings|undefined} value */
proto.is.vision.CameraConfig.prototype.setImage = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.is.vision.CameraConfig.prototype.clearImage = function() {
  this.setImage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.is.vision.CameraConfig.prototype.hasImage = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional CameraSettings camera = 3;
 * @return {?proto.is.vision.CameraSettings}
 */
proto.is.vision.CameraConfig.prototype.getCamera = function() {
  return /** @type{?proto.is.vision.CameraSettings} */ (
    jspb.Message.getWrapperField(this, proto.is.vision.CameraSettings, 3));
};


/** @param {?proto.is.vision.CameraSettings|undefined} value */
proto.is.vision.CameraConfig.prototype.setCamera = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.is.vision.CameraConfig.prototype.clearCamera = function() {
  this.setCamera(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.is.vision.CameraConfig.prototype.hasCamera = function() {
  return jspb.Message.getField(this, 3) != null;
};


